# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

## Mod Properties
mod_id=gleeful_creepers
mod_name=Gleeful Creepers
mod_license=MIT
mod_version=1.1.0
# used for publishing, human-readable
mod_loader=Fabric

mod_group_id=net.vercte
mod_authors=Vercte
mod_description=delightful creeper! lush and gleeful in nature

## Mod Dependencies
fabric_api_version=0.155.3+26.1.2
forge_config_api_port_version=26.1.5

mod_menu_version=18.0.0