license = "${mod_license}"
issueTrackerURL="https://github.com/vercte/gleeful-creepers/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/gleeful-creepers/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/gleeful-creepers"
logoFile="icon.png"
credits="BellHop for dreaming about the Gleeper"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange= "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
